### ISSUE TITLE
add to Operate First deployment of ODH

### ISSUE THREAD

**Issue by goern** [AICoE/pricingnbs#2]
**Is your feature request related to a problem? Please describe.**
As the Owner of this Repository,
I want Operate-First to continuously deploy the notebooks in this repo,
so that I can show them to the world (r/o view).

**Describe the solution you'd like**
A combination of AICoE-CI and Op1st-CD

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/kind feature
/assign @TreeinRandomForest 

Cc: @pacospace

**Comment by durandom** [comment]
Wouldnt the notebook be deployed on a release anyway? Or rather made available for deployment via JupyterHub.

Or do we want to run the notebook on a schedule, so that we can expose the runtime usage metrics, such CPU and MEM?
See https://github.com/operate-first/support/issues/61

**Comment by goern** [comment]
Hmm, I think its two fold: 1. release container image on tag 2. Job for each notebook to be executed, that job could even be a periodic Prow job (aka integration test)

**Comment by pacospace** [comment]
@TreeinRandomForest let's do it :D 

you should follow this single file here: https://github.com/AICoE/manage-dependencies-tutorial/blob/master/docs/thoth-aicoe-services.md

I will create another repo just for this and nothing else.

**Comment by codificat** [comment]
> let's do it :D

I assume this implies a desire to
/remove-lifecycle rotten

**Comment by TreeinRandomForest** [comment]
@pacospace While I have read/write rights in AICoE, I can't add collaborators (to add sesheta). Can you see the repository settings button?

**Comment by pacospace** [comment]
> @pacospace While I have read/write rights in AICoE, I can't add collaborators (to add sesheta). Can you see the repository settings button?

Me neither, only owners of the org can, but I think all repositories created in AICoE should have the bot as collaborator, @goern can you confirm please?

**Comment by goern** [comment]
there is no new commit in the past 9 months, do we still want to have this repo deployed? can we use meteor for it?

**Comment by pacospace** [comment]
> there is no new commit in the past 9 months, do we still want to have this repo deployed? can we use meteor for it?

Yes we can also use meteor for this.
